### ISSUE TITLE
Talk Proposal: Generating TypeScript with TypeScript

### ISSUE THREAD

**Issue by bennycode** [berlinjs/berlinjs.org#301] opened 2019-09-09 14:57 UTC
### Talk title

Generating TypeScript with TypeScript

### Abstract 

In the information age, more and more tasks are being performed by machines. Cars drive autonomously, drones deliver packages and voice-controlled assistants read the daily news. All these automations are possible through code. But can we write code to automate writing code? 
 
In our presentation we want to take you on a journey how to generate an entire application tier. As a practical example we will design a REST API client generator with TypeScript 3. For the interface definition we will use Swagger 2.0.

### Your name (and pronouns)

Benny Neugebauer (he/him) & Florian Keller (he/him)

- [x] This will be our first tech talk

### Contact Details

- Benny Neugebauer / @bennyn / benny@wire.com
- Florian Keller / @ffflorian / berlinjs@floriankeller.de

You can link to Benny's Twitter handle ([@apfelbenny](https://twitter.com/apfelbenny)). Florian doesn't have a Twitter account.

### Code of Conduct

- [x] We have read and agree to the [BerlinJS Code of Conduct](http://berlincodeofconduct.org/)

**Comment by carolstran** [comment] 2019-10-07 19:02
Hey hey @bennyn and @ffflorian! Apologies for my delay, but thanks for submitting a talk 🙌 I like the title especially 😄 I've added you to our internal waitlist and we'll let you know when we'll be able to have you.

Our 2019 lineups are all full, but you'll have our first choice of 2020 meetups since it'll be your first talk. The Q1 dates are January 16, February 20 and March 19 if any of those already work for you.

**Comment by bennycode** [comment] 2019-10-09 16:54
@carolstran Thanks for your reply and giving us the choice to select a date in 2020. To open the season we pick the first meetup in 2020, which is January, 16th. 🍀

**Comment by carolstran** [comment] 2019-10-27 15:06
Excellent - consider it confirmed! We'll check in again closer to 🎉

**Comment by carolstran** [comment] 2020-01-06 05:44
Hey hey @bennyn, just wanted to check in and see if you and Florian are still up for giving a talk at our meetup later this month (Thursday, January 16) 🎉 And if yes, then please let me know if you want to make any changes to the title/abstract before we add it to the website 🥂

**Comment by bennycode** [comment] 2020-01-07 17:17
Hi @carolstran, thanks for asking.

We are still keen on giving the talk next Thursday (January, 16th). We have been thinking about our talk and we would like to adjust the title and description to give it more clarity.

**New title:** 
Code Generation with TypeScript

**New abstract:** 
Introduction to TypeScript's Compiler API which can be used to generate functional TypeScript code in an automatic manner. You will learn about TypeScript's abstract syntax tree (AST) and how to use it to construct consistent and maintainable source code.

It will be a "Feature Talk" (15-25 minutes).

**Comment by carolstran** [comment] 2020-01-09 08:46
Great thank you! I'll add you both to the website today.

**Comment by carolstran** [comment] 2020-01-13 07:07
👋 @bennyn and @ffflorian, we added your talk to [our website](https://berlinjs.org/) and [tweeted about it](https://twitter.com/berlinjs/status/1215196087532818433?s=20). Just so you know, @SaraVieira will be the only organizer at the meetup on Thursday, so please find her and check-in when you arrive 😊

Co.up has an assortment of doggles, etc. - but if you need anything specific for your talk, please just let us know. Looking forward to it 🎉

**Comment by bennycode** [comment] 2020-01-13 17:05
Thanks for the promotion! We will also retweet from [@wire](https://twitter.com/wire). 📢

We will bring our own tech equipment but great to hear that there is a backup. 
Will there also be a recording of the talks? 🎥

Looking forward to Thursday! 🙂

**Comment by carolstran** [comment] 2020-01-20 11:37
👋 @bennyn and @ffflorian, thank you again for giving a talk at our January meetup! I was sad to miss it, but it seems like it went very well. I'll close the issue now, but always feel free to reach out if you have any feedback 😊

**Closed as completed by carolstran** 2020-01-20 11:37 UTC
Labels: Confirmed 🎉, Feature 🎤

**Comment by ffflorian** [comment] 2020-01-20 12:17
Thanks for having us, it was great :slightly_smiling_face: 

By the way, for all interested: The slides and the code examples can be found in our [repository](https://github.com/ffflorian/code-generation-with-ts).

**Comment by carolstran** [comment] 2020-01-20 12:26
Oh great! Would it be alright if I tweeted the link from the BerlinJS account?

**Comment by ffflorian** [comment] 2020-01-20 12:27
> Would it be alright if I tweeted the link from the BerlinJS account?

Of course!
