### ISSUE TITLE
Talk proposal: Talk to the customer!

### ISSUE THREAD

**Issue by sameoldmadness** [berlinjs/berlinjs.org#297] opened 2019-07-30 15:00 UTC
### Talk title

Talk to the customer!

### Abstract 

In big companies developers tends to be separated from the customers by customer support, managers, etc.

I would share a story on how a product could benefit from a direct communication between developer and customer.

Original talk in Russian is 25 minutes, but could be scaled down to 10.

### Your name (and pronouns)

Roman Paradeev

- [x] This will be my first tech talk (in English)

### Contact Details

@sameoldmadness at twitter/telegram

### Code of Conduct

- [x] I've read and agree to the [BerlinJS Code of Conduct](http://berlincodeofconduct.org/)

**Comment by carolstran** [comment] 2019-07-30 18:27
👋 @sameoldmadness, thanks for submitting a talk to our meetup! This topic is super important too. Would you be available for either our October 17 or November 21 meetup?

**Comment by sameoldmadness** [comment] 2019-07-30 18:46
October would be great!

I'd also be ready to give a talk on a short notice in case you'll need a
replacement.

**Comment by carolstran** [comment] 2019-07-31 09:38
Sounds good, we'll mark you down as confirmed October for now and check in again towards the end of September. Thanks @sameoldmadness! 🎉

**Comment by carolstran** [comment] 2019-08-28 21:50
Hey hey @sameoldmadness, would you be able to give the talk at our September meetup instead? It'll be on Thursday, September 19.

No pressure, just thought I'd ask because we had a cancellation 😊

**Comment by sameoldmadness** [comment] 2019-08-29 08:40
This would be perfect!

Is there a need for a dry run?

**Comment by carolstran** [comment] 2019-08-29 21:27
Amazing thank you! We'll update the website next week, so if you want to make any changes to your title/abstract - just let me know.

No need for a dry run on our end, but if you'd like to do one then we're happy to arrange that!

**Comment by sameoldmadness** [comment] 2019-09-01 15:23
For me title/abstract look fine.

What would be the length of the talk?

**Comment by carolstran** [comment] 2019-09-03 14:15
Sounds great - I'll get you up on the website this week 😊 

Oh sorry, I thought I had mentioned that. Would 10 minutes be alright? We could probably go up to 15 but unfortunately, that's the maximum as we have a very full lineup for September.

**Comment by carolstran** [comment] 2019-09-03 14:36
👋 PS. I've added you to the website! https://berlinjs.org/ Now we're just waiting to add one more speaker before announcing.

**Comment by sameoldmadness** [comment] 2019-09-04 08:53
10 minutes is perfect, thank you.

**Comment by carolstran** [comment] 2019-10-01 23:27
Thanks again for giving a talk, I heard it went very well 😊  Closing this issue now 👋

**Closed as completed by carolstran** 2019-10-01 23:27 UTC
Labels: Confirmed 🎉, Lightning ⚡️
