### ISSUE TITLE
Hooks everywhere - Apollo/GraphQL is no exception

### ISSUE THREAD

**Issue by vilvaathibanpb** [berlinjs/berlinjs.org#286] opened 2019-05-24 16:56 UTC
##### Talk title

Hooks everywhere - Apollo/GraphQL is no exception

##### Abstract

The fame of Apollo/GraphQL and React Hooks are increasing every day. Many have already started using both in production. Now React hooks are possible in Apollo Client as well. Anyone who used Render props pattern of Apollo client will definitely love the way how hooks make the code readable and elegant. My talk will be on how to use hooks with Apollo client.

###### Your name

Vilva Athiban P B

###### Means to get in touch with you

twitter - @vilvaathibanpb
email - vilvaathiban@gmail.com

You may link my twitter to your page.

**Comment by rmehner** [comment] 2019-05-27 09:32
👋 Thanks for the proposal. How long would your talk be and what dates would work best for you?

**Comment by vilvaathibanpb** [comment] 2019-05-27 09:50
Hello Robin,  It will be somewhere around 15-20 minutes (includes a small live demo as well) . And i am flexible with any date after June 7th. All I need is a confirmation 2 or 3 days prior to the talk.

**Comment by rmehner** [comment] 2019-05-27 09:54
Perfect :) I'll put you on our list for after June :) We'll get back to you then.

**Comment by vilvaathibanpb** [comment] 2019-05-27 09:57
@rmehner Makes sense. Will be waiting for an update from your side :)

**Comment by carolstran** [comment] 2019-06-23 18:21
👋 @vilvaathibanpb, quick question for you. Would this be your first talk? Just wondering because that would bump you up on the waitlist. 

Also is there any chance that you'd be open to delivering a 5-10 minute version of your talk? If not, no worries - we can keep you on the regular waitlist. I'm trying to think of ways to get more people on our stage before the end of 2019  🤔💡 ⚡️ 🚀

**Comment by vilvaathibanpb** [comment] 2019-06-23 19:00
@carolstran  Hello, This might be my first talk in Berlin / Germany. But overall I have experience speaking in few meetups in India. Also, If its gonna be a 10 minute talk, may be I can give a theoretical version of the talk. If I have to do a practical demo / live coding , 10 minutes will not be enough. 

Please let me know what do you think. Thanks

**Comment by carolstran** [comment] 2019-06-23 19:03
You don't have to do anything, it's entirely up to you 😊 

Would you want to give a 10-minute talk or prefer to wait and give a longer version?

**Comment by vilvaathibanpb** [comment] 2019-06-23 19:18
@carolstran May be I will go with the 10 minutes one now. It might be a good start to talk in Berlin and I can improve and give longer talks in later points.

**Comment by carolstran** [comment] 2019-06-23 19:26
Awesome! Ok I'm going to label this issue with a ⚡️ 

Once I hear back from everyone else, then we can talk about dates 🙌

**Comment by vilvaathibanpb** [comment] 2019-06-24 08:18
Sounds good. :)

**Comment by carolstran** [comment] 2019-07-19 14:22
👋 Hello again! If you'd be ok giving the 10-minute version of your talk, then we can fit you in this year for sure. Are you available for either the September 19, October 17 or November 21 meetup?

**Comment by vilvaathibanpb** [comment] 2019-07-19 15:41
Hey @carolstran  I am ok with the 10-minute version of the talk and I am available for September 19. :) Let me know if it works for you

**Comment by carolstran** [comment] 2019-07-20 11:35
Yes that works! I'll mark you as confirmed for September and we'll check in again towards the end of August 😊

**Comment by vilvaathibanpb** [comment] 2019-07-22 13:02
Sure. I will definitely be available on that date :)

**Comment by carolstran** [comment] 2019-08-21 12:29
👋 @vilvaathibanpb  

Just wanted to check in to see if you're still available and want to give a lightning talk at our meetup on September 19? And if so, is the title and abstract you provided above correct?

If you could let me know either way by the end of the month, that'd be excellent 😁

**Comment by vilvaathibanpb** [comment] 2019-08-21 13:08
@carolstran I am available and would love to give the talk on September 19th :) I have modified the abstract a little.

Talk title
Hooks everywhere - Apollo/GraphQL is no exception

Abstract
The fame of Apollo/GraphQL and React Hooks are increasing every day. Many have already started using both in production. Apollo Client has recently released Hooks. Anyone who used Render props pattern of Apollo client will definitely love the way how hooks make the code readable and elegant. My talk will be on how to use hooks with Apollo client.

**Comment by carolstran** [comment] 2019-08-22 08:43
Great thanks @vilvaathibanpb! Looking forward to it. Once we hear back from the other speakers, we'll update the website 😁

**Comment by vilvaathibanpb** [comment] 2019-08-22 09:04
@carolstran Can you hold on till next Monday? I might have to travel to Prague in September for 2 days officially and not sure about the dates yet. I will give you a confirmation on Monday about this. I guess it should be ok if I confirm before End of month right?

**Comment by vilvaathibanpb** [comment] 2019-08-26 14:41
@carolstran As I feared, my official trip to Prague is scheduled on September 19-20. Is it possible to push my talk to October meetup?

Thanks

**Comment by carolstran** [comment] 2019-08-28 21:48
Aww bummer for us but Prague is so nice, you'll have a great time!

As of now, the October lineup is full... but I'm pretty sure we can move things around. Let me check with my co-organizers and get back to you 😊

**Comment by vilvaathibanpb** [comment] 2019-08-29 15:30
@carolstran  Thanks :) And yes let me know if you find some slot in October or November

**Comment by carolstran** [comment] 2019-08-29 21:29
Alright looks like October would work 😁 So if you could just confirm and let me know if Thursday, October 17 works for you - that'd be great.

**Comment by vilvaathibanpb** [comment] 2019-08-30 08:09
Yes @carolstran . October 17 definitely works for me and I cross-verified that there are no more events until x-mas party in Office :) So this is good

**Comment by carolstran** [comment] 2019-08-31 12:10
Great, thanks @vilvaathibanpb! And no stress even if it does change again, we totally understand 😊 We'll check in again towards the end of September but for now - looking forward to it 🎉

**Comment by carolstran** [comment] 2019-10-02 17:29
Hey hey @vilvaathibanpb, just wanted to check in and see if you're still up for giving a talk at our meetup later this month (October 17) 👻 And if yes, then please let me know if you want to make any changes to your title/abstract before we add it to the website 🎃

**Comment by vilvaathibanpb** [comment] 2019-10-03 22:13
Hi @carolstran , You can use the same title and abstract and I am available on Oct 17th :)

**Comment by carolstran** [comment] 2019-10-07 18:54
Great, so I've updated the website - just let me know if we should change anything: https://berlinjs.org/ Planning to announce on Twitter tomorrow!

**Comment by carolstran** [comment] 2019-10-21 16:04
👋 @vilvaathibanpb, thank you again for giving a talk at our October meetup! I was very sad to miss it, but it seems like it was well-received! I'll close the issue now, but always feel free to reach out 😊

**Closed as completed by carolstran** 2019-10-21 16:04 UTC
Labels: Confirmed 🎉, Lightning ⚡️
